name: Build Himeko-NovaSR


on:
  push:
    branches:
      - main

  workflow_dispatch:


permissions:
  contents: write



jobs:


  build:


    strategy:

      fail-fast: false

      matrix:

        include:

          - name: linux-x64
            target: x86_64-linux

          - name: linux-arm64
            target: aarch64-linux

          - name: windows-x64
            target: x86_64-windows



    runs-on: ubuntu-latest



    steps:


      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0



      # 修复 Linux 大小写问题
      - name: Fix filename case
        run: |

          git config core.ignorecase false

          if [ -f gameserver/src/session.zig ]; then
              mv gameserver/src/session.zig gameserver/src/Session.zig
          fi



      - name: Install Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.14.1



      - name: Build

        run: |

          zig build \
          -Dtarget=${{ matrix.target }} \
          -Doptimize=ReleaseFast



      - name: Prepare release

        run: |

          mkdir release


          cp zig-out/bin/* release/ || true


          cp -r resources release/
          cp -r lua release/
          cp -r protocol release/


          cp frecsr-data.json release/
          cp hotfix.json release/



          echo "Build:"
          ls -la release



      - name: Package

        run: |

          cd release

          zip -r ../Himeko-NovaSR-${{ matrix.name }}.zip .



      - name: Upload

        uses: actions/upload-artifact@v4

        with:

          name: Himeko-NovaSR-${{ matrix.name }}

          path:

            Himeko-NovaSR-${{ matrix.name }}.zip





  release:


    needs: build

    runs-on: ubuntu-latest



    steps:


      - name: Download

        uses: actions/download-artifact@v4



      - name: Release

        uses: softprops/action-gh-release@v2

        with:

          tag_name: build-${{ github.run_number }}

          name: Himeko-NovaSR Build ${{ github.run_number }}

          files: |

            **/*.zip


        env:

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
